const BAD_REQUEST = 400;
const REQUEST_REFUSED = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const USER_EXISTS = 409;
const UNAUTHORIZED = 401;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  USER_EXISTS,
  UNAUTHORIZED,
  REQUEST_REFUSED,
};
